<?php
    if (function_exists('vc_map')) {
        vc_map( array(
            "name"                          => __( "TS Video Youtube", "ts_visual_composer_extend" ),
            "base"                          => "TS-VCSC-Youtube",
            "icon" 	                        => "icon-wpb-ts_vcsc_youtube",
            "class"                         => "",
            "category"                      => __( "VC Extensions", "ts_visual_composer_extend" ),
            "description"                   => __("Place a YouTube Video", "ts_visual_composer_extend"),
            "admin_enqueue_js"              => "",
            "admin_enqueue_css"             => "",
            "params"                        => array(
                // YouTube Video				
                array(
                    "type"                  => "seperator",
                    "heading"               => __( "", "ts_visual_composer_extend" ),
                    "param_name"            => "seperator_1",
					"value"					=> "",
                    "seperator"				=> "Youtube Video",
                    "description"           => __( "", "ts_visual_composer_extend" )
                ),
				array(
					"type"                  => "dropdown",
					"heading"               => __( "YouTube Content", "ts_visual_composer_extend" ),
					"param_name"            => "content_type",
                    "value"                 => array(
                        __("Single Video", "ts_visual_composer_extend")          			=> "video",
                        __("Defined Playlist", "ts_visual_composer_extend")         		=> "playlist",
						__("Playlist via Search Term(s)", "ts_visual_composer_extend")		=> "searchterm",
						__("Playlist from Individual Videos", "ts_visual_composer_extend")	=> "combination",
						__("Playlist from User Uploads", "ts_visual_composer_extend")		=> "uploads",
                    ),
					"admin_label"           => true,
					"description"           => __( "Select the type of trigger to click on in order to show the lightbox.", "ts_visual_composer_extend" ),					
				),
                array(
                    "type"                  => "textfield",
                    "heading"               => __( "YouTube Video URL", "ts_visual_composer_extend" ),
                    "param_name"            => "content_youtube",
                    "value"                 => "",
                    "admin_label"           => true,
                    "description"           => __( "Enter the URL for the YouTube video.", "ts_visual_composer_extend" ),
                    "dependency"            => array( 'element' => "content_type", 'value' => 'video' ),
                ),
                array(
                    "type"                  => "textfield",
                    "heading"               => __( "YouTube Playlist ID", "ts_visual_composer_extend" ),
                    "param_name"            => "content_playlist",
                    "value"                 => "",
                    "admin_label"           => true,
                    "description"           => __( "Enter the URL or ID for a PUBLIC YouTube playlist; playlist ID must start with 'PL'.", "ts_visual_composer_extend" ),
                    "dependency"            => array( 'element' => "content_type", 'value' => 'playlist' ),
                ),
                array(
                    "type"                  => "textfield",
                    "heading"               => __( "YouTube Search Term(s)", "ts_visual_composer_extend" ),
                    "param_name"            => "content_search",
                    "value"                 => "",
                    "admin_label"           => true,
                    "description"           => __( "Enter the search term(s) for videos on YouTube; playlist will show a maximum of 20 videos.", "ts_visual_composer_extend" ),
                    "dependency"            => array( 'element' => "content_type", 'value' => 'searchterm' ),
                ),
                array(
                    "type"                  => "textfield",
                    "heading"               => __( "YouTube Video ID's", "ts_visual_composer_extend" ),
                    "param_name"            => "content_combination",
                    "value"                 => "",
                    "admin_label"           => true,
                    "description"           => __( "Enter the ID's of up to 20 videos, separated by comma to build a custom playlist.", "ts_visual_composer_extend" ),
                    "dependency"            => array( 'element' => "content_type", 'value' => 'combination' ),
                ),
                array(
                    "type"                  => "textfield",
                    "heading"               => __( "YouTube User ID", "ts_visual_composer_extend" ),
                    "param_name"            => "content_uploads",
                    "value"                 => "",
                    "admin_label"           => true,
                    "description"           => __( "Enter the User ID of the user whose videos should be shown in a playlist.", "ts_visual_composer_extend" ),
                    "dependency"            => array( 'element' => "content_type", 'value' => 'uploads' ),
                ),
                array(
                    "type"                  => "nouislider",
                    "heading"               => __( "Start Time", "ts_visual_composer_extend" ),
                    "param_name"            => "video_start",
                    "value"                 => "0",
                    "min"                   => "0",
                    "max"                   => "7200",
                    "step"                  => "1",
                    "unit"                  => 's',
                    "description"           => __( "Select a time in seconds at which the video should begin playing; must be smaller than 'End Time'; set to 0 (zero) to disable.", "ts_visual_composer_extend" ),
					"dependency"            => array( 'element' => "content_type", 'value' => 'video' ),
                ),
                array(
                    "type"                  => "nouislider",
                    "heading"               => __( "End Time", "ts_visual_composer_extend" ),
                    "param_name"            => "video_end",
                    "value"                 => "0",
                    "min"                   => "0",
                    "max"                   => "7200",
                    "step"                  => "1",
                    "unit"                  => 's',
                    "description"           => __( "Select a time in seconds at which the video should stop playing; must be larger than 'Start Time'; set to 0 (zero) to disable..", "ts_visual_composer_extend" ),
					"dependency"            => array( 'element' => "content_type", 'value' => 'video' ),
                ),				
				array(
					"type"              	=> "switch",
					"heading"			    => __( "Show Related Videos", "ts_visual_composer_extend" ),
					"param_name"		    => "video_related",
					"value"             	=> "false",
					"on"					=> __( 'Yes', "ts_visual_composer_extend" ),
					"off"					=> __( 'No', "ts_visual_composer_extend" ),
					"style"					=> "select",
					"design"				=> "toggle-light",
					"description"		    => __( "Switch the toggle if you want to show related videos at the end of the video.", "ts_visual_composer_extend" ),
                    "dependency"            => ""
				),
				array(
					"type"              	=> "switch",
					"heading"			    => __( "Autoplay Video", "ts_visual_composer_extend" ),
					"param_name"		    => "lightbox_play",
					"value"             	=> "false",
					"on"					=> __( 'Yes', "ts_visual_composer_extend" ),
					"off"					=> __( 'No', "ts_visual_composer_extend" ),
					"style"					=> "select",
					"design"				=> "toggle-light",
					"description"		    => __( "Switch the toggle if you want to auto-play the video once opened in the lightbox or on pageload (iFrame).", "ts_visual_composer_extend" ),
                    "dependency"            => ""
				),
				// Lightbox Settings
				array(
					"type"				    => "seperator",
					"heading"			    => __( "", "ts_visual_composer_extend" ),
					"param_name"		    => "seperator_3",
					"value"					=> "",
					"seperator"				=> "Trigger Settings",
					"description"		    => __( "", "ts_visual_composer_extend" ),
					"group"					=> "Lightbox Settings",
				),
				array(
					"type"              	=> "switch",
					"heading"           	=> __( "Open in Lightbox", "ts_visual_composer_extend" ),
					"param_name"        	=> "content_lightbox",
					"value"             	=> "false",
					"on"					=> __( 'Yes', "ts_visual_composer_extend" ),
					"off"					=> __( 'No', "ts_visual_composer_extend" ),
					"style"					=> "select",
					"design"				=> "toggle-light",
					"description"       	=> __( "Switch the toggle to show the video in a lightbox.", "ts_visual_composer_extend" ),
					"group" 				=> "Lightbox Settings",
				),
                // Triggger Type
				array(
					"type"                  => "dropdown",
					"heading"               => __( "Trigger Type", "ts_visual_composer_extend" ),
					"param_name"            => "content_youtube_trigger",
                    "value"                 => array(
                        __("Default Image", "ts_visual_composer_extend")          				=> "default",
                        __("Custom Image", "ts_visual_composer_extend")           				=> "image",
						__("YouTube Cover (Single Video)", "ts_visual_composer_extend")			=> "preview",
						__("YouTube Cover (Defined Playlist)", "ts_visual_composer_extend")		=> "playcover",
						__("YouTube Cover (Individual Videos)", "ts_visual_composer_extend")	=> "coverfirst",
						__("YouTube User Image (User Uploads)", "ts_visual_composer_extend")	=> "usercover",
                        __("Font Icon", "ts_visual_composer_extend")              				=> "icon",
                        __("Winged Button", "ts_visual_composer_extend")          				=> "winged",
                        __("Simple Button", "ts_visual_composer_extend")          				=> "simple",
                        __("Text", "ts_visual_composer_extend")                   				=> "text",
                        __("Custom HTML", "ts_visual_composer_extend")            				=> "custom",
                    ),
					"description"           => __( "Select the type of trigger to click on in order to show the lightbox.", "ts_visual_composer_extend" ),
					"dependency"            => array( 'element' => "content_lightbox", 'value' => 'true' ),
					"group" 				=> "Lightbox Settings",
				),
                // Custom Image
				array(
					"type"                  => "attach_image",
					"heading"               => __( "Select Image", "ts_visual_composer_extend" ),
					"param_name"            => "content_youtube_image",
					"value"                 => "",
					"description"           => __( "Select the preview image for the lightbox content.", "ts_visual_composer_extend" ),
					"dependency"            => array( 'element' => "content_youtube_trigger", 'value' => 'image' ),
					"group" 				=> "Lightbox Settings",
				),
				array(
					"type"              	=> "switch",
					"heading"			    => __( "Simple Image Only", "ts_visual_composer_extend" ),
					"param_name"		    => "content_youtube_image_simple",
					"value"             	=> "false",
					"on"					=> __( 'Yes', "ts_visual_composer_extend" ),
					"off"					=> __( 'No', "ts_visual_composer_extend" ),
					"style"					=> "select",
					"design"				=> "toggle-light",
					"description"		    => __( "Switch the toggle if you want display just the image without any styling.", "ts_visual_composer_extend" ),
                    "dependency"            => array( 'element' => "content_youtube_trigger", 'value' => 'image' ),
					"group" 				=> "Lightbox Settings",
				),
                array(
                    "type"                  => "dropdown",
                    "heading"               => __( "Auto Height Setting", "ts_visual_composer_extend" ),
                    "param_name"            => "content_image_height",
                    "width"                 => 150,
                    "value"                 => array(
                        __( '100% Height Setting', "ts_visual_composer_extend" )		=> "height: 100%;",
                        __( 'Auto Height Setting', "ts_visual_composer_extend" )     	=> "height: auto;",
                    ),
                    "description"           => __( "Select what CSS height setting should be applied to the image (change only if image height does not display correctly).", "ts_visual_composer_extend" ),
                    "dependency"            => array( 'element' => "content_youtube_trigger", 'value' => array('preview', 'default', 'image', 'playcover', 'usercover') ),
					"group" 				=> "Lightbox Settings",
                ),
                // Font Icon
				array(
					'type' 					=> $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_IconSelectorType,
					'heading' 				=> __( 'Select Icon', 'ts_visual_composer_extend' ),
					'param_name' 			=> 'content_youtube_icon',
					'value'					=> '',
					'source'				=> $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_IconSelectorValue,
					'settings' 				=> array(
						'emptyIcon' 				=> false,
						'type' 						=> 'extensions',
						'iconsPerPage' 				=> $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_IconSelectorPager,
						'source' 					=> $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_IconSelectorSource,
					),
					"description"       	=> ($VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_EditorVisualSelector == "true" ? __( "Select the icon you want to display.", "ts_visual_composer_extend" ) : $VISUAL_COMPOSER_EXTENSIONS->TS_VCSC_IconSelectorString),
					"dependency"            => array( 'element' => "content_youtube_trigger", 'value' => 'icon' ),
					"group" 				=> "Lightbox Settings",
				),	
				array(
					"type"                  => "nouislider",
					"heading"               => __( "Icon Size", "ts_visual_composer_extend" ),
					"param_name"            => "content_youtube_iconsize",
					"value"                 => "30",
					"min"                   => "16",
					"max"                   => "512",
					"step"                  => "1",
					"unit"                  => 'px',
					"description"           => __( "Select the icon / image size", "ts_visual_composer_extend" ),
					"dependency"            => array( 'element' => "content_youtube_trigger", 'value' => 'icon' ),
					"group" 				=> "Lightbox Settings",
				),
				array(
					"type"                  => "colorpicker",
					"heading"               => __( "Icon Color", "ts_visual_composer_extend" ),
					"param_name"            => "content_youtube_iconcolor",
					"value"                 => "#cccccc",
					"description"           => __( "Define the color of the icon.", "ts_visual_composer_extend" ),
					"dependency"            => array( 'element' => "content_youtube_trigger", 'value' => 'icon' ),
					"group" 				=> "Lightbox Settings",
				),
                // Button
                array(
                    "type"                  => "textfield",
                    "heading"               => __( "Button Text", "ts_visual_composer_extend" ),
                    "param_name"            => "content_youtube_buttontext",
                    "value"                 => "View Video",
                    "description"           => __( "Enter the text for the button.", "ts_visual_composer_extend" ),
                    "dependency"            => array( 'element' => "content_youtube_trigger", 'value' => array('winged', 'simple') ),
					"group" 				=> "Lightbox Settings",
                ),
                // Text Link
                array(
                    "type"                  => "textfield",
                    "heading"               => __( "Trigger Text", "ts_visual_composer_extend" ),
                    "param_name"            => "content_youtube_text",
                    "value"                 => "",
                    "description"           => __( "Enter the trigger text for the video.", "ts_visual_composer_extend" ),
                    "dependency"            => array( 'element' => "content_youtube_trigger", 'value' => 'text' ),
					"group" 				=> "Lightbox Settings",
                ),
                // Custom Code
                array(
                    "type"                  => "textarea_raw_html",
                    "heading"               => __("Raw HTML", "ts_visual_composer_extend"),
                    "param_name"            => "content_raw",
                    "value"                 => base64_encode(""),
                    "description"           => __("Enter your custom HTML code; code will be wrapped in appropriate link automatically.", "ts_visual_composer_extend"),
                    "dependency"            => array( 'element' => "content_youtube_trigger", 'value' => 'custom' ),
					"group" 				=> "Lightbox Settings",
                ),
                // Title + Subtitle
                array(
                    "type"                  => "textfield",
                    "heading"               => __( "Title", "ts_visual_composer_extend" ),
                    "param_name"            => "content_youtube_title",
                    "value"                 => "",
                    "description"           => __( "Enter a title for the lightbox content.", "ts_visual_composer_extend" ),
                    "dependency"            => array( 'element' => "content_youtube_trigger", 'value' => array('image', 'default', 'preview', 'playcover', 'usercover', 'winged') ),
					"group" 				=> "Lightbox Settings",
                ),
                array(
                    "type"                  => "textfield",
                    "heading"               => __( "Subtitle", "ts_visual_composer_extend" ),
                    "param_name"            => "content_youtube_subtitle",
                    "value"                 => "",
                    "description"           => __( "Enter a subtitle for the lightbox content.", "ts_visual_composer_extend" ),
                    "dependency"            => array( 'element' => "content_youtube_trigger", 'value' => array('winged') ),
					"group" 				=> "Lightbox Settings",
                ),
                // Lightbox Settings
				array(
					"type"				    => "seperator",
					"heading"			    => __( "", "ts_visual_composer_extend" ),
					"param_name"		    => "seperator_2",
					"value"				    => "Lightbox Settings",
					"description"		    => __( "", "ts_visual_composer_extend" ),
                    "dependency"            => array( 'element' => "content_lightbox", 'value' => "true" ),
					"group" 				=> "Lightbox Settings",
				),
                array(
                    "type"                  => "textfield",
                    "heading"               => __( "Group Name", "ts_visual_composer_extend" ),
                    "param_name"            => "lightbox_group_name",
                    "value"                 => "nachogroup",
                    "description"           => __( "Enter a custom group name to manually build group with other non-gallery items; leave empty for non-grouping", "ts_visual_composer_extend" ),
                    "dependency"            => array( 'element' => "content_lightbox", 'value' => "true" ),
					"group" 				=> "Lightbox Settings",
                ),
                array(
                    "type"                  => "dropdown",
                    "heading"               => __( "Transition Effect", "ts_visual_composer_extend" ),
                    "param_name"            => "lightbox_effect",
                    "width"                 => 150,
                    "value"                 => array(
						__( 'Random', "ts_visual_composer_extend" )       	=> "random",
						__( 'Swipe', "ts_visual_composer_extend" )        	=> "swipe",
						__( 'Fade & Swipe', "ts_visual_composer_extend" )	=> "fade",
						__( 'Scale', "ts_visual_composer_extend" )        	=> "scale",
						__( 'Slide Up', "ts_visual_composer_extend" )     	=> "slideUp",
						__( 'Slide Down', "ts_visual_composer_extend" )   	=> "slideDown",
						__( 'Flip', "ts_visual_composer_extend" )         	=> "flip",
						__( 'Skew', "ts_visual_composer_extend" )         	=> "skew",
						__( 'Bounce Up', "ts_visual_composer_extend" )    	=> "bounceUp",
						__( 'Bounce Down', "ts_visual_composer_extend" )  	=> "bounceDown",
						__( 'Break In', "ts_visual_composer_extend" )     	=> "breakIn",
						__( 'Rotate In', "ts_visual_composer_extend" )    	=> "rotateIn",
						__( 'Rotate Out', "ts_visual_composer_extend" )   	=> "rotateOut",
						__( 'Hang Left', "ts_visual_composer_extend" )    	=> "hangLeft",
						__( 'Hang Right', "ts_visual_composer_extend" )   	=> "hangRight",
						__( 'Cycle Up', "ts_visual_composer_extend" )     	=> "cicleUp",
						__( 'Cycle Down', "ts_visual_composer_extend" )   	=> "cicleDown",
						__( 'Zoom In', "ts_visual_composer_extend" )      	=> "zoomIn",
						__( 'Throw In', "ts_visual_composer_extend" )     	=> "throwIn",
						__( 'Fall', "ts_visual_composer_extend" )         	=> "fall",
						__( 'Jump', "ts_visual_composer_extend" )         	=> "jump",
                    ),
                    "admin_label"           => true,
                    "description"           => __( "Select the transition effect to be used for the image in the lightbox.", "ts_visual_composer_extend" ),
                    "dependency"            => array( 'element' => "content_lightbox", 'value' => "true" ),
					"group" 				=> "Lightbox Settings",
                ),
                // Tooltip Settings
				array(
					"type"				    => "seperator",
					"heading"			    => __( "", "ts_visual_composer_extend" ),
					"param_name"		    => "seperator_4",
					"value"					=> "",
					"seperator"				=> "Tooltip Settings",
					"description"		    => __( "", "ts_visual_composer_extend" ),
					"group" 				=> "Tooltip Settings",
				),
				array(
					"type"              	=> "switch",
					"heading"           	=> __( "Use HTML Tooltip", "ts_visual_composer_extend" ),
					"param_name"        	=> "content_tooltip_html",
					"value"             	=> "false",
					"on"					=> __( 'Yes', "ts_visual_composer_extend" ),
					"off"					=> __( 'No', "ts_visual_composer_extend" ),
					"style"					=> "select",
					"design"				=> "toggle-light",
					"description"		    => __( "Switch the toggle if you want to apply a tooltip with HTML code to the element.", "ts_visual_composer_extend" ),
					"group" 				=> "Tooltip Settings",
				),
				array(
					"type"				    => "textarea",
					"class"				    => "",
					"heading"			    => __( "Tooltip Content", "ts_visual_composer_extend" ),
					"param_name"		    => "content_tooltip_content",
					"value"				    => "",
					"description"		    => __( "Enter the tooltip content here (do not use quotation marks or HTML code).", "ts_visual_composer_extend" ),
					"dependency"            => array( 'element' => "content_tooltip_html", 'value' => "false" ),
					"group" 				=> "Tooltip Settings",
				),
				array(
					"type"              	=> "textarea_raw_html",
					"heading"           	=> __( "Tooltip Content", "ts_visual_composer_extend" ),
					"param_name"        	=> "content_tooltip_encoded",
					"value"             	=> base64_encode(""),
					"description"      	 	=> __( "Enter the tooltip content here (HTML code can be used).", "ts_visual_composer_extend" ),
					"dependency"            => array( 'element' => "content_tooltip_html", 'value' => "true" ),
					"group" 				=> "Tooltip Settings",
				),
				array(
					"type"				    => "dropdown",
					"class"				    => "",
					"heading"			    => __( "Tooltip Position", "ts_visual_composer_extend" ),
					"param_name"		    => "content_tooltip_position",
                    "value"                 => array(
                        __("Top", "ts_visual_composer_extend")                    => "ts-simptip-position-top",
                        __("Bottom", "ts_visual_composer_extend")                 => "ts-simptip-position-bottom",
                    ),
					"description"		    => __( "Select the tooltip position in relation to the image.", "ts_visual_composer_extend" ),
					"group" 				=> "Tooltip Settings",
				),
				array(
					"type"				    => "dropdown",
					"class"				    => "",
					"heading"			    => __( "Tooltip Style", "ts_visual_composer_extend" ),
					"param_name"		    => "content_tooltip_style",
                    "value"                 => array(
                        __("Black", "ts_visual_composer_extend")                  => "",
                        __("Gray", "ts_visual_composer_extend")                   => "ts-simptip-style-gray",
                        __("Green", "ts_visual_composer_extend")                  => "ts-simptip-style-green",
                        __("Blue", "ts_visual_composer_extend")                   => "ts-simptip-style-blue",
                        __("Red", "ts_visual_composer_extend")                    => "ts-simptip-style-red",
                        __("Orange", "ts_visual_composer_extend")                 => "ts-simptip-style-orange",
                        __("Yellow", "ts_visual_composer_extend")                 => "ts-simptip-style-yellow",
                        __("Purple", "ts_visual_composer_extend")                 => "ts-simptip-style-purple",
                        __("Pink", "ts_visual_composer_extend")                   => "ts-simptip-style-pink",
                        __("White", "ts_visual_composer_extend")                  => "ts-simptip-style-white",
                    ),
					"description"		    => __( "Select the tooltip style.", "ts_visual_composer_extend" ),
					"group" 				=> "Tooltip Settings",
				),
				array(
					"type"					=> "nouislider",
					"heading"				=> __( "Tooltip X-Offset", "ts_visual_composer_extend" ),
					"param_name"			=> "tooltipster_offsetx",
					"value"					=> "0",
					"min"					=> "-100",
					"max"					=> "100",
					"step"					=> "1",
					"unit"					=> 'px',
					"description"			=> __( "Define an optional X-Offset for the tooltip position.", "ts_visual_composer_extend" ),
					"group" 				=> "Tooltip Settings",
				),
				array(
					"type"					=> "nouislider",
					"heading"				=> __( "Tooltip Y-Offset", "ts_visual_composer_extend" ),
					"param_name"			=> "tooltipster_offsety",
					"value"					=> "0",
					"min"					=> "-100",
					"max"					=> "100",
					"step"					=> "1",
					"unit"					=> 'px',
					"description"			=> __( "Define an optional Y-Offset for the tooltip position.", "ts_visual_composer_extend" ),
					"group" 				=> "Tooltip Settings",
				),
				// Other Settings
				array(
					"type"				    => "seperator",
					"heading"			    => __( "", "ts_visual_composer_extend" ),
					"param_name"		    => "seperator_5",
					"value"					=> "",
					"seperator"				=> "Other Settings",
					"description"		    => __( "", "ts_visual_composer_extend" ),
					"group"					=> "Other Settings",
				),
                array(
                    "type"                  => "nouislider",
                    "heading"               => __( "Margin: Top", "ts_visual_composer_extend" ),
                    "param_name"            => "margin_top",
                    "value"                 => "0",
                    "min"                   => "0",
                    "max"                   => "200",
                    "step"                  => "1",
                    "unit"                  => 'px',
                    "description"           => __( "Select the top margin for the element.", "ts_visual_composer_extend" ),
					"group"					=> "Other Settings",
                ),
                array(
                    "type"                  => "nouislider",
                    "heading"               => __( "Margin: Bottom", "ts_visual_composer_extend" ),
                    "param_name"            => "margin_bottom",
                    "value"                 => "0",
                    "min"                   => "0",
                    "max"                   => "200",
                    "step"                  => "1",
                    "unit"                  => 'px',
                    "description"           => __( "Select the bottom margin for the element.", "ts_visual_composer_extend" ),
					"group"					=> "Other Settings",
                ),
				array(
					"type"                  => "textfield",
					"heading"               => __( "Define ID Name", "ts_visual_composer_extend" ),
					"param_name"            => "el_id",
					"value"                 => "",
					"description"           => __( "Enter an unique ID for the element.", "ts_visual_composer_extend" ),
					"group"					=> "Other Settings",
				),
				array(
					"type"                  => "textfield",
					"heading"               => __( "Extra Class Name", "ts_visual_composer_extend" ),
					"param_name"            => "el_class",
					"value"                 => "",
					"description"           => __( "Enter a class name for the element.", "ts_visual_composer_extend" ),
					"group"					=> "Other Settings",
				),
				array(
					"type"                  => "load_file",
					"heading"               => __( "", "ts_visual_composer_extend" ),
                    "param_name"            => "el_file",
					"value"                 => "",
					"file_type"             => "js",
					"file_path"             => "js/ts-visual-composer-extend-element.min.js",
					"description"           => __( "", "ts_visual_composer_extend" )
				),
            ))
        );
    }
?>